# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://Meng1024.github.io
date_format: "ordinal"
title: Meng
subtitle: "Notebook"
description: "Meng's blog"
keywords: Algorithm, Meng
timezone: PST
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Meng
organization:
organization_url:
github_username: Meng1024
location: US
email: mengmeng2811@gamil.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 20
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner:
    repo:
    oauth:
        client_id:
        client_secret:
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: Meng1024
    repo: blog-comments
    clientID: 6fa190e321d18d91ac18
    clientSecret: 93bc614907a7a8c1c6f6deb85a64248a227533c0
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-139451660-1
